<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nicks-MacBook-Pro.local" name="Default test" tests="20" failures="1" timestamp="20 Nov 2016 21:04:31 GMT" time="54.64" errors="0">
  <testcase name="test01_addEmployees on null(test.TestDatabase)" time="0.512" classname="test.TestDatabase"/>
  <testcase name="test02_addProducts on null(test.TestDatabase)" time="0.935" classname="test.TestDatabase"/>
  <testcase name="test03_addCustomers on null(test.TestDatabase)" time="1.247" classname="test.TestDatabase"/>
  <testcase name="test04_addAccounts on null(test.TestDatabase)" time="0.734" classname="test.TestDatabase"/>
  <testcase name="test05_addComplaints on null(test.TestDatabase)" time="0.149" classname="test.TestDatabase"/>
  <testcase name="test06_addAccidents on null(test.TestDatabase)" time="0.149" classname="test.TestDatabase"/>
  <testcase name="test07_getDateAndTimeForProduct on null(test.TestDatabase)" time="0.186" classname="test.TestDatabase"/>
  <testcase name="test08_getProductsMadeByWorker on null(test.TestDatabase)" time="0.33" classname="test.TestDatabase"/>
  <testcase name="test09_getErrorByQC on null(test.TestDatabase)" time="0.11" classname="test.TestDatabase"/>
  <testcase name="test10_getCostProduct3RepairedBy on null(test.TestDatabase)" time="0.111" classname="test.TestDatabase"/>
  <testcase name="test11_getCustomerWhoPurchasedAllColor on null(test.TestDatabase)" time="0.14" classname="test.TestDatabase"/>
  <testcase name="test12_getWorkDaysLostFromRepairs on null(test.TestDatabase)" time="0.038" classname="test.TestDatabase"/>
  <testcase name="test13_getAllCustomersWhoAreWorkers on null(test.TestDatabase)" time="0.071" classname="test.TestDatabase"/>
  <testcase name="test14_customersPurchasedOwn on null(test.TestDatabase)" time="0.07" classname="test.TestDatabase"/>
  <testcase name="test15_averageCostProductYear on null(test.TestDatabase)" time="0.037" classname="test.TestDatabase"/>
  <testcase name="test16_switchTSandQC on null(test.TestDatabase)" time="0.218" classname="test.TestDatabase"/>
  <testcase name="test17_deleteAccidentsInRange on null(test.TestDatabase)" time="0.146" classname="test.TestDatabase"/>
  <testcase name="test19_export on null(test.TestDatabase)" time="0.115" classname="test.TestDatabase"/>
  <testcase name="test20_quit on null(test.TestDatabase)" time="0.001" classname="test.TestDatabase"/>
  <testcase name="test21_Error on null(test.TestDatabase)" time="43.139" classname="test.TestDatabase">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at test.TestDatabase.test21_Error(TestDatabase.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- test21_Error on null(test.TestDatabase) -->
</testsuite> <!-- Default test -->
